language: php

php:
  - 7.1
  - 7.2

before_script:
  - sudo apt-get update

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - php tests/tests.php
  - vendor/bin/phpstan analyse src
